<?php

namespace Jardiland\ProduitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{
    public function getLastProduit() {
        $maxResults = 6;
         $produits = $this->createQueryBuilder('p')
                      ->orderBy('p.id','DESC')
                      ->setMaxResults($maxResults)
                      ->getQuery()
                      ->execute()
            ;
        return $produits;
    }
    
    
}
